name: Laravel Autograde

on: [push]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Dependencies
        run: composer install

      - name: Run PHPUnit Tests
        run: php artisan test
commit msg: Add Laravel autograding workflow
